# Generated by Django 3.1.4 on 2020-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item1',
            new_name='ItemA',
        ),
        migrations.RenameModel(
            old_name='item2',
            new_name='ItemB',
        ),
        migrations.RenameModel(
            old_name='item3',
            new_name='ItemC',
        ),
    ]
